# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: app/services/price/price.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='app/services/price/price.proto',
  package='',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1e\x61pp/services/price/price.proto\" \n\x0cPriceRequest\x12\x10\n\x08\x65xchange\x18\x01 \x02(\t\".\n\x0bPriceObject\x12\x10\n\x08\x63urrency\x18\x01 \x02(\t\x12\r\n\x05price\x18\x02 \x02(\t\"5\n\x15PriceMultipleResponse\x12\x1c\n\x06prices\x18\x01 \x03(\x0b\x32\x0c.PriceObject29\n\x05Price\x12\x30\n\x07get_all\x12\r.PriceRequest\x1a\x16.PriceMultipleResponse'
)




_PRICEREQUEST = _descriptor.Descriptor(
  name='PriceRequest',
  full_name='PriceRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='exchange', full_name='PriceRequest.exchange', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=66,
)


_PRICEOBJECT = _descriptor.Descriptor(
  name='PriceObject',
  full_name='PriceObject',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='currency', full_name='PriceObject.currency', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='price', full_name='PriceObject.price', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=68,
  serialized_end=114,
)


_PRICEMULTIPLERESPONSE = _descriptor.Descriptor(
  name='PriceMultipleResponse',
  full_name='PriceMultipleResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='prices', full_name='PriceMultipleResponse.prices', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=116,
  serialized_end=169,
)

_PRICEMULTIPLERESPONSE.fields_by_name['prices'].message_type = _PRICEOBJECT
DESCRIPTOR.message_types_by_name['PriceRequest'] = _PRICEREQUEST
DESCRIPTOR.message_types_by_name['PriceObject'] = _PRICEOBJECT
DESCRIPTOR.message_types_by_name['PriceMultipleResponse'] = _PRICEMULTIPLERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PriceRequest = _reflection.GeneratedProtocolMessageType('PriceRequest', (_message.Message,), {
  'DESCRIPTOR' : _PRICEREQUEST,
  '__module__' : 'app.services.price.price_pb2'
  # @@protoc_insertion_point(class_scope:PriceRequest)
  })
_sym_db.RegisterMessage(PriceRequest)

PriceObject = _reflection.GeneratedProtocolMessageType('PriceObject', (_message.Message,), {
  'DESCRIPTOR' : _PRICEOBJECT,
  '__module__' : 'app.services.price.price_pb2'
  # @@protoc_insertion_point(class_scope:PriceObject)
  })
_sym_db.RegisterMessage(PriceObject)

PriceMultipleResponse = _reflection.GeneratedProtocolMessageType('PriceMultipleResponse', (_message.Message,), {
  'DESCRIPTOR' : _PRICEMULTIPLERESPONSE,
  '__module__' : 'app.services.price.price_pb2'
  # @@protoc_insertion_point(class_scope:PriceMultipleResponse)
  })
_sym_db.RegisterMessage(PriceMultipleResponse)



_PRICE = _descriptor.ServiceDescriptor(
  name='Price',
  full_name='Price',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=171,
  serialized_end=228,
  methods=[
  _descriptor.MethodDescriptor(
    name='get_all',
    full_name='Price.get_all',
    index=0,
    containing_service=None,
    input_type=_PRICEREQUEST,
    output_type=_PRICEMULTIPLERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_PRICE)

DESCRIPTOR.services_by_name['Price'] = _PRICE

# @@protoc_insertion_point(module_scope)
